name: Build and Upload Project
on:
  push:
    tags:
        - v* # Only build if there is a version tag.
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: storm-front 
  ITCH_USER: supriseorb

jobs:
  buildForWindows:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.1f1
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

  deployToItch:
    name: Deploy game to itch.io
    runs-on: ubuntu-latest
    needs: [buildForWindows]
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: Build
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        CHANNEL: windows-x86
        PACKAGE: Build/StandaloneWindows
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        CHANNEL: windows-x64
        PACKAGE: Build/StandaloneWindows64
    # Delete the artifact after we upload it to itch.io
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: build